// Case studies — admin list (all statuses). Password-gated on
// REVLIENT_ADMIN_PASSWORD via x-admin-key. Auto-generated by the cron;
// admins review + publish here. The public blog reads the separate
// /api/case-studies/published endpoint (no auth, published only).
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_PASSWORD = process.env.REVLIENT_ADMIN_PASSWORD;

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });
}

function checkAuth(req) {
  const key = req.headers.get("x-admin-key");
  return Boolean(ADMIN_PASSWORD) && key === ADMIN_PASSWORD;
}

export async function GET(request) {
  if (!checkAuth(request)) return json({ error: "Unauthorized" }, 401);
  if (!SUPABASE_URL || !SUPABASE_KEY) return json({ error: "Server not configured" }, 500);

  try {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/case_studies?select=*&order=created_at.desc`,
      {
        headers: {
          apikey: SUPABASE_KEY,
          Authorization: `Bearer ${SUPABASE_KEY}`,
          Accept: "application/json",
        },
        cache: "no-store",
      }
    );

    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      return json({ error: "Supabase request failed", status: res.status, detail }, 502);
    }

    const rows = await res.json();
    return json({ case_studies: Array.isArray(rows) ? rows : [] });
  } catch (err) {
    return json({ error: "Fetch failed", detail: String(err?.message || err) }, 500);
  }
}
